# Generated by Django 4.2.7 on 2025-10-31 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurements", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodymeasurement",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "身体測定",
                "verbose_name_plural": "身体測定",
            },
        ),
        migrations.AlterModelOptions(
            name="progresslog",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "進捗記録",
                "verbose_name_plural": "進捗記録",
            },
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="arms_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="左腕 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="arms_right",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="右腕 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="body_fat_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="体脂肪率 %",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="calves_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="左ふくらはぎ (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="calves_right",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="右ふくらはぎ (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="chest",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="胸囲 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="date",
            field=models.DateField(verbose_name="測定日"),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="身長（センチメートル）",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="身長 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="hips",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="ヒップ (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="muscle_mass",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="筋肉量 (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="neck",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="首周り (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="notes",
            field=models.TextField(blank=True, verbose_name="メモ"),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="measurement_photos/",
                verbose_name="進捗写真",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="shoulders",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="肩幅 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="thighs_left",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="左太もも (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="thighs_right",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="右太もも (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="waist",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="ウエスト (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="bodymeasurement",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="体重 (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="achievements",
            field=models.TextField(blank=True, verbose_name="達成したこと"),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="challenges",
            field=models.TextField(blank=True, verbose_name="課題"),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="date",
            field=models.DateField(verbose_name="記録日"),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="energy_level",
            field=models.IntegerField(
                help_text="エネルギーレベルを評価 (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="エネルギーレベル",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="mood",
            field=models.IntegerField(
                help_text="気分を評価 (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="気分",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="notes",
            field=models.TextField(blank=True, verbose_name="メモ"),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="sleep_hours",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="睡眠時間",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="sleep_quality",
            field=models.IntegerField(
                help_text="睡眠の質を評価 (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="睡眠の質",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="soreness_level",
            field=models.IntegerField(
                help_text="筋肉痛のレベルを評価 (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="筋肉痛レベル",
            ),
        ),
        migrations.AlterField(
            model_name="progresslog",
            name="stress_level",
            field=models.IntegerField(
                help_text="ストレスレベルを評価 (1-10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="ストレスレベル",
            ),
        ),
    ]
