# Generated by Django 4.2.7 on 2025-10-24 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_meal_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meal_items",
                to="nutrition.food",
            ),
        ),
        migrations.AddField(
            model_name="mealitem",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nutrition.meal",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_foods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="favoritemealitem",
            name="favorite_meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="nutrition.favoritemeal",
            ),
        ),
        migrations.AddField(
            model_name="favoritemealitem",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nutrition.food"
            ),
        ),
        migrations.AddField(
            model_name="favoritemeal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_meals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favoritefood",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="nutrition.food",
            ),
        ),
        migrations.AddField(
            model_name="favoritefood",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_foods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "date"], name="nutrition_m_user_id_80eec6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["meal_type"], name="nutrition_m_meal_ty_a544b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="nutrition_f_name_caa2b0_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["category"], name="nutrition_f_categor_32643c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritefood",
            unique_together={("user", "food")},
        ),
    ]
