# Generated by Django 4.2.7 on 2025-10-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoritefood",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "お気に入り食品",
                "verbose_name_plural": "お気に入り食品",
            },
        ),
        migrations.AlterModelOptions(
            name="favoritemeal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "お気に入り食事",
                "verbose_name_plural": "お気に入り食事",
            },
        ),
        migrations.AlterModelOptions(
            name="favoritemealitem",
            options={"verbose_name": "お気に入り食事項目", "verbose_name_plural": "お気に入り食事項目"},
        ),
        migrations.AlterModelOptions(
            name="food",
            options={
                "ordering": ["name"],
                "verbose_name": "食品",
                "verbose_name_plural": "食品",
            },
        ),
        migrations.AlterModelOptions(
            name="meal",
            options={
                "ordering": ["-date", "-time"],
                "verbose_name": "食事",
                "verbose_name_plural": "食事",
            },
        ),
        migrations.AlterModelOptions(
            name="mealitem",
            options={"verbose_name": "食事項目", "verbose_name_plural": "食事項目"},
        ),
        migrations.AlterModelOptions(
            name="mealplan",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "食事プラン",
                "verbose_name_plural": "食事プラン",
            },
        ),
        migrations.AlterField(
            model_name="favoritemeal",
            name="description",
            field=models.TextField(blank=True, verbose_name="説明"),
        ),
        migrations.AlterField(
            model_name="favoritemeal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "朝食"),
                    ("lunch", "昼食"),
                    ("dinner", "夕食"),
                    ("snack", "間食"),
                ],
                max_length=20,
                verbose_name="食事タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="favoritemeal",
            name="name",
            field=models.CharField(max_length=200, verbose_name="食事名"),
        ),
        migrations.AlterField(
            model_name="food",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="ブランド"),
        ),
        migrations.AlterField(
            model_name="food",
            name="category",
            field=models.CharField(
                choices=[
                    ("protein", "タンパク質"),
                    ("carbs", "炭水化物"),
                    ("fats", "脂質"),
                    ("vegetables", "野菜"),
                    ("fruits", "果物"),
                    ("dairy", "乳製品"),
                    ("grains", "穀物"),
                    ("snacks", "スナック"),
                    ("beverages", "飲料"),
                    ("other", "その他"),
                ],
                max_length=20,
                verbose_name="カテゴリー",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=200, verbose_name="食品名"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="date",
            field=models.DateField(verbose_name="日付"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="meal_images/", verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "朝食"),
                    ("lunch", "昼食"),
                    ("dinner", "夕食"),
                    ("snack", "間食"),
                ],
                max_length=20,
                verbose_name="食事タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="name",
            field=models.CharField(max_length=200, verbose_name="食事名"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="notes",
            field=models.TextField(blank=True, verbose_name="メモ"),
        ),
        migrations.AlterField(
            model_name="meal",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="時間"),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="goal",
            field=models.CharField(
                choices=[
                    ("weight_loss", "減量"),
                    ("muscle_gain", "筋肉増強"),
                    ("maintenance", "維持"),
                    ("endurance", "持久力"),
                ],
                max_length=50,
                verbose_name="目標",
            ),
        ),
    ]
