# Generated by Django 4.2.7 on 2025-11-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0003_alter_favoritefood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "減量"),
                    ("muscle_gain", "筋肉増強"),
                    ("maintenance", "維持"),
                    ("endurance", "持久力"),
                ],
                default="maintenance",
                max_length=50,
                verbose_name="目標",
            ),
        ),
    ]
