# Generated by Django 4.2.7 on 2025-11-11 02:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nutrition", "0004_alter_mealplan_description_alter_mealplan_goal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="レシピ名")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Calories (kcal)",
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Protein (g)",
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Carbs (g)",
                    ),
                ),
                (
                    "fats",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Fats (g)",
                    ),
                ),
                ("time", models.CharField(max_length=50, verbose_name="調理時間")),
                ("servings", models.CharField(max_length=50, verbose_name="人数")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipe_images/",
                        verbose_name="画像",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "レシピ",
                "verbose_name_plural": "レシピ",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="nutrition_r_user_id_9053a0_idx",
                    )
                ],
            },
        ),
    ]
