# Generated by Django 4.2.7 on 2025-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0005_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="unit",
            field=models.CharField(
                default="g",
                help_text="Unit of measurement (g, ml, 個, etc.)",
                max_length=20,
                verbose_name="Unit",
            ),
        ),
        migrations.AlterField(
            model_name="food",
            name="serving_size",
            field=models.DecimalField(
                decimal_places=1,
                default=100,
                help_text="Default serving size",
                max_digits=6,
                verbose_name="Serving Size",
            ),
        ),
    ]
