# Generated by Django 4.2.7 on 2025-11-07 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="current_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="現在の体重（キログラム）",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="現在の体重 (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "男性"), ("female", "女性"), ("other", "その他")],
                max_length=10,
                null=True,
                verbose_name="性別",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="身長（センチメートル）",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="身長 (cm)",
            ),
        ),
    ]
