# Generated by Django 4.2.7 on 2025-11-17 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userprofile_current_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_body_fat_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="体脂肪率目標",
            ),
        ),
    ]
