# Generated by Django 4.2.7 on 2025-10-31 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodpreference",
            options={"verbose_name": "食品の好み", "verbose_name_plural": "食品の好み"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "ユーザープロフィール", "verbose_name_plural": "ユーザープロフィール"},
        ),
        migrations.AlterField(
            model_name="foodpreference",
            name="allergies",
            field=models.TextField(
                blank=True, help_text="食物アレルギーをリスト（カンマ区切り）", verbose_name="アレルギー"
            ),
        ),
        migrations.AlterField(
            model_name="foodpreference",
            name="avoid_ingredients",
            field=models.TextField(
                blank=True, help_text="避けたい食材（カンマ区切り）", verbose_name="避けたい食材"
            ),
        ),
        migrations.AlterField(
            model_name="foodpreference",
            name="diet_type",
            field=models.CharField(
                choices=[
                    ("omnivore", "雑食"),
                    ("vegetarian", "ベジタリアン"),
                    ("vegan", "ビーガン"),
                    ("pescatarian", "ペスカタリアン"),
                    ("keto", "ケトジェニック"),
                    ("paleo", "パレオ"),
                    ("mediterranean", "地中海式"),
                ],
                default="omnivore",
                max_length=20,
                verbose_name="食事タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="foodpreference",
            name="dislikes",
            field=models.TextField(
                blank=True, help_text="嫌いな食べ物（カンマ区切り）", verbose_name="嫌いな食べ物"
            ),
        ),
        migrations.AlterField(
            model_name="foodpreference",
            name="preferred_foods",
            field=models.TextField(
                blank=True, help_text="好きな食べ物（カンマ区切り）", verbose_name="好きな食べ物"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="生年月日"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="メールアドレス"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="電話番号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="プロフィール画像",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "座りがち（ほとんど運動なし）"),
                    ("light", "軽い活動（週1-3日の軽い運動）"),
                    ("moderate", "中程度の活動（週3-5日の中程度の運動）"),
                    ("very", "活発（週6-7日のハードな運動）"),
                    ("extra", "非常に活発（非常にハードな運動、肉体労働）"),
                ],
                default="moderate",
                max_length=20,
                verbose_name="活動レベル",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="arms",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="腕周り (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="body_fat_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="体脂肪率",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="calves",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="ふくらはぎ (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="chest",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="胸囲 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="現在の体重（キログラム）",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="現在の体重 (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="fitness_goal",
            field=models.CharField(
                choices=[
                    ("weight_loss", "減量"),
                    ("muscle_gain", "筋肉増強"),
                    ("maintenance", "維持"),
                    ("endurance", "持久力"),
                    ("flexibility", "柔軟性"),
                    ("general_fitness", "総合的なフィットネス"),
                ],
                default="general_fitness",
                max_length=20,
                verbose_name="フィットネス目標",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "男性"), ("female", "女性"), ("other", "その他")],
                max_length=10,
                verbose_name="性別",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                help_text="身長（センチメートル）",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="身長 (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hips",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="ヒップ (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="目標体重（キログラム）",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="目標体重 (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="thighs",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="太もも (cm)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="waist",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="ウエスト (cm)",
            ),
        ),
    ]
