# Generated by Django 4.2.7 on 2025-10-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "初級"),
                    ("intermediate", "中級"),
                    ("advanced", "上級"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(
                choices=[
                    ("none", "器具なし"),
                    ("dumbbells", "ダンベル"),
                    ("barbell", "バーベル"),
                    ("machine", "マシン"),
                    ("bodyweight", "自重"),
                    ("resistance_band", "レジスタンスバンド"),
                    ("kettlebell", "ケトルベル"),
                    ("other", "その他"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("strength", "筋力トレーニング"),
                    ("cardio", "有酸素運動"),
                    ("flexibility", "柔軟性"),
                    ("balance", "バランス"),
                    ("sports", "スポーツ"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "初級"),
                    ("intermediate", "中級"),
                    ("advanced", "上級"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="goal",
            field=models.CharField(
                choices=[
                    ("weight_loss", "減量"),
                    ("muscle_gain", "筋肉増強"),
                    ("strength", "筋力向上"),
                    ("endurance", "持久力"),
                    ("general_fitness", "総合的なフィットネス"),
                ],
                max_length=50,
            ),
        ),
    ]
