# Generated by Django 4.2.7 on 2025-11-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workouts",
            "0002_alter_exercise_difficulty_alter_exercise_equipment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="exercises/"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("strength", "筋力トレーニング"),
                    ("cardio", "有酸素運動"),
                    ("flexibility", "柔軟性"),
                    ("balance", "バランス"),
                    ("sports", "スポーツ"),
                    ("gym", "ジム"),
                ],
                max_length=20,
            ),
        ),
    ]
