# Generated by Django 4.2.7 on 2025-11-13 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0003_exercise_image_alter_exercise_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("strength", "筋力トレーニング"),
                    ("cardio", "有酸素運動"),
                    ("flexibility", "柔軟性"),
                    ("balance", "バランス"),
                    ("sports", "スポーツ"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExerciseMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "画像"), ("video", "動画")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Image or video file", upload_to="exercises/media/"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="External URL (optional)", null=True
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="workouts.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Exercise Media",
                "ordering": ["exercise", "order", "created_at"],
            },
        ),
    ]
