# Generated by Django 4.2.7 on 2025-11-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0005_exercise_met_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="is_template",
            field=models.BooleanField(default=False, help_text="テンプレートとして利用可能なプラン"),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for categorization (e.g., '初心者', '自宅', 'ジム')",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutschedule",
            name="completion_percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="完了率（パーセンテージ）", max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="workoutschedule",
            name="current_day",
            field=models.IntegerField(default=1, help_text="現在の日番号"),
        ),
        migrations.AddField(
            model_name="workoutschedule",
            name="current_week",
            field=models.IntegerField(default=1, help_text="現在の週番号"),
        ),
        migrations.AddField(
            model_name="workoutschedule",
            name="total_workouts_completed",
            field=models.IntegerField(default=0),
        ),
    ]
