# Generated by Django 4.2.7 on 2025-11-14 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0006_workoutplan_is_template_workoutplan_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="is_template",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="workoutplan",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="workoutschedule",
            name="completion_percentage",
        ),
        migrations.RemoveField(
            model_name="workoutschedule",
            name="current_day",
        ),
        migrations.RemoveField(
            model_name="workoutschedule",
            name="current_week",
        ),
        migrations.RemoveField(
            model_name="workoutschedule",
            name="total_workouts_completed",
        ),
    ]
