# Generated by Django 4.2.7 on 2025-11-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0007_remove_workoutplan_is_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="instructions",
            field=models.TextField(blank=True, help_text="Step-by-step instructions"),
        ),
    ]
